language: node_js
notifications:
  email: maykonluiscapellari@gmail.com
node_js:
- 5.2.0
services:
- mongodb
env:
  global:
  - NODE_ENV: test
addons:
  sauce_connect: true
before_install:
- npm install -g bower
- npm install -g grunt-cli
- npm install -g karma-cli
- npm install -g protractor
- webdriver-manager update
- bower install
before_script:
- node test/data.js
- grunt minifica
script:
- karma start config/karma.config.js --single-run --browsers PhantomJS
before_deploy:
- git config --global user.email 'maykonluiscapellari@gmail.com'
- git config --global user.name 'Maykon Luís Capellari'
- git checkout $TRAVIS_BRANCH
- git add --all
- git commit -am "Travis commit"
deploy:
  provider: openshift
  user: maykonluiscapellari@gmail.com
  password:
    secure: hhpgO4monCV7So6OOl+EZyOmU4HNXKegX/S9YCM7s2O00/+4AhxeOUyUCm/JCw9FfvG75p5g0DWcol9mmfT4tYhX4f0JiG/WPfhcKSdeqCOCneoOd/1Yz2DWI6BYXS+bjn1i+4fOAe5cqERYb2qscOYwldR7vneUQwZXdK9rFARbPh2wgV5k94RxwKhULmjKkqRfrSTAvgSbo8UojOFOMGG+7q9Hxg6CzkPVc/uoB6RKhEPY5ImaWMuQrAQLp4ZL1tdmVa/zVDkBPj4AIuJihHG52jK45FBspu+5VJ9BhQzk/K9VP7mgkiISyI3/MphC0QZVhWhHaI4u9XFMzVuInnbNkRsvxrXK0l99zuvNEc/snPTBwEZ967FMN8v/4OT09CE+OzmFxBnsfJZszwnsHsWPA6Vky3oy2LZdFHdHt88glW0y5CAelWLIes5gpBzSRuKd0VhSU2U7nUdcDIdr231fHrxeVe6kfHla5ROQvjTBYli+6lNnHjOFZeZ3+Hq3igsHLcVxcWG87Q5zgHlWyc8ie1uQN3ZRIQ2VOsAAWC8tBWniT1wlvEdzJOXC7tGWqXbJEikJfy1nnCkgoyfXjnwejJhRBQR3RnHjchEW8HGlz6jaDr5a52t38h/6iBB1s7OmpLV1ybpjPjBE/24nWeyTo5L4bU4N18IHXbEhLYs=
  app: contatooh
  domain: capellari
  on:
    repo: maykon/contatooh
